In [ ]:
import pandas as pd
import category_encoders as ce
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
df = pd.read_csv("category_dataset.csv", index_col = False)
df.head()

In [3]:
def change_class(data):
    lst = ['TCP port & service discovery','Stealth scan OS & version detection','Malware']
    if data in lst:
        return "Malware stealth scan"
    else:
        return data

In [4]:
df["Class"] = df["Class"].apply(change_class)

In [5]:
X = df[['Source IP', 'Destination IP', 'Source MAC', 'Destination MAC', 'Protocol', 'Flags', 'Src Port', 'Dst Port',
       'Length']].values
y_category = df["Class"].values

In [6]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
le = LabelEncoder()
y_category = le.fit_transform(y_category)

In [7]:
ce_bin = ce.BinaryEncoder(return_df=False)
enc_bin = ce_bin.fit(X)
X = enc_bin.transform(X)

c:\users\admin\appdata\local\programs\python\python38\lib\site-packages\category_encoders\utils.py:21: FutureWarning: is_categorical is deprecated and will be removed in a future version.  Use is_categorical_dtype instead
  elif pd.api.types.is_categorical(cols):


In [8]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y_category, test_size=0.34)

In [9]:
import pandas as pd
import numpy as np
from sklearn.metrics import roc_auc_score, accuracy_score, precision_score, recall_score, f1_score
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis, QuadraticDiscriminantAnalysis
from sklearn.cluster import KMeans
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import precision_recall_fscore_support
from sklearn.metrics import mean_squared_error as mse
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import cross_validate
from sklearn.model_selection import train_test_split
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.feature_selection import SelectFromModel
from sklearn.svm import LinearSVC
from sklearn.ensemble import VotingClassifier
from sklearn.feature_selection import RFECV

In [10]:
X[0]

array([    0,     0,     0,     0,     1,     0,     0,     0,     0,
           1,     0,     0,     0,     0,     0,     0,     0,     1,
           0,     0,     0,     0,     0,     0,     0,     0,     1,
           0,     0,     0,     1,     0,     0,     0,     0,     1,
       60394,   502,    64], dtype=int64)

In [13]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
sc_enc = sc.fit(X_train)
X_train = sc_enc.transform(X_train)
X_test = sc_enc.transform(X_test)

In [15]:
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
MinMaxScaler = preprocessing.MinMaxScaler()
X_data_minmax = MinMaxScaler.fit_transform(X)

In [16]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y_category, test_size=0.34)

In [17]:
knn_clf=KNeighborsClassifier()
knn_clf.fit(X_train,y_train)
ypred=knn_clf.predict(X_test)

In [21]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
result = confusion_matrix(y_test, ypred)
print("Confusion Matrix")
print(result)
result1 = classification_report(y_test, ypred)
print("Classification Report:")
print (result1)
result2 = accuracy_score(y_test,ypred)
print("Accuracy:",result2)

Confusion Matrix
[[ 952   58    0    0    0    0    0]
 [  73  973    0    3    0    0    0]
 [   0    0 1003    0    0    0    0]
 [   4   13   37 3097   39   16  104]
 [   0    0   52   27  999    0    0]
 [   0    0    0   24    2  934    6]
 [   7    8    0   52    3    1  946]]
Classification Report:
              precision    recall  f1-score   support

           0       0.92      0.94      0.93      1010
           1       0.92      0.93      0.93      1049
           2       0.92      1.00      0.96      1003
           3       0.97      0.94      0.95      3310
           4       0.96      0.93      0.94      1078
           5       0.98      0.97      0.97       966
           6       0.90      0.93      0.91      1017

    accuracy                           0.94      9433
   macro avg       0.94      0.95      0.94      9433
weighted avg       0.94      0.94      0.94      9433

Accuracy: 0.9439202798685465


In [ ]:
from sklearn.svm import SVC
svm_model_linear = SVC(kernel = 'linear', C = 1).fit(X_train, y_train)
svm_predictions = svm_model_linear.predict(X_test)
  
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
result = confusion_matrix(y_test, svm_predictions)
print("Confusion Matrix")
print(result)
result1 = classification_report(y_test, svm_predictions)
print("Classification Report:")
print (result1)
result2 = accuracy_score(y_test,svm_predictions)
print("Accuracy:",result2)